### ISSUE TITLE
When database dir not set.

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidatorapp#3]
```
lib/GeneValidatorApp.rb:144:in `init_database': uninitialized constant Module::DATABASE_DIR_NOT_SET (NameError)
    from /Users/priyam/wurmlab/GeneValidatorApp/lib/GeneValidatorApp.rb:46:in `init'
    from bin/genevalidatorapp:110:in `<main>'
```

**Comment by IsmailM** [comment]
Fixed in #13
